matrix:
  include:
    - language: python
      python: 3.6
      install:
        - pip install -r requirements.txt
      script:
        - pylint starlight
        - mypy starlight
        - python manage.py test
