# Generated by Django 2.1.2 on 2018-10-16 13:28

import channel2.apps.data.models.tag_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='cover_image',
            field=models.FileField(null=True, upload_to=channel2.apps.data.models.tag_model.cover_image_upload_to),
        ),
    ]
